# -*- coding: utf-8 -*-
"""Execute backend-contract smoke checks against a HIVM operation backend.

This runner does not implement rewrite itself.  It standardizes how the Python
side asks a real vTriton/HivmOpsEditor backend to prove that a generated
four-Plan backend contract is consumable:

1. print capabilities
2. inventory
3. roundtrip
4. verify-only
5. dry-run with edit-script/contract
6. optional mutate with edit-script/contract

The bundled fake backend can pass the plumbing tests, but any report with
``is_real_mlir_backend == False`` must not be used as production rewrite proof.
"""
from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

RUNNER_SCHEMA_VERSION = "hivm_backend_contract_execution_v1"


@dataclass
class CommandResult:
    name: str
    argv: List[str]
    returncode: int
    stdout: str
    stderr: str
    report_path: Optional[str] = None
    output_path: Optional[str] = None

    @property
    def ok(self) -> bool:
        return self.returncode == 0

    def to_json(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "argv": self.argv,
            "returncode": self.returncode,
            "ok": self.ok,
            "stdout_preview": self.stdout[:4000],
            "stderr_preview": self.stderr[:4000],
            "report_path": self.report_path,
            "output_path": self.output_path,
        }


def _load_json_if_exists(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover - defensive diagnostics
        return {"_json_load_error": str(exc)}


def _run(name: str, argv: Sequence[str], report_path: Optional[Path] = None, output_path: Optional[Path] = None) -> CommandResult:
    cp = subprocess.run(list(argv), text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return CommandResult(
        name=name,
        argv=list(argv),
        returncode=cp.returncode,
        stdout=cp.stdout,
        stderr=cp.stderr,
        report_path=str(report_path) if report_path else None,
        output_path=str(output_path) if output_path else None,
    )


def _capability_object(result: CommandResult, report_path: Path) -> Dict[str, Any]:
    obj: Dict[str, Any]
    try:
        obj = json.loads(result.stdout.strip() or "{}")
    except Exception:
        obj = {"raw_stdout": result.stdout.strip(), "parse_error": True}
    obj.setdefault("backend_returncode", result.returncode)
    report_path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")
    return obj


def _backend_arg_prefix(backend: Path) -> List[str]:
    # Python scripts are invoked via the current interpreter so they work even
    # when the executable bit is lost after zip extraction on Windows.
    if backend.suffix == ".py":
        return [sys.executable, str(backend)]
    return [str(backend)]


def execute_backend_contract(
    backend: Path,
    ir_path: Path,
    contract_path: Path,
    output_dir: Path,
    *,
    run_mutate: bool = False,
    mutation_kind: str = "contract_smoke",
) -> Dict[str, Any]:
    """Run the standardized backend contract smoke sequence.

    Parameters
    ----------
    backend:
        Path to ``hivm-operation-backend`` or the local fake backend fixture.
    ir_path:
        Input ``.hivm.mlir``.
    contract_path:
        JSON contract/edit-script generated by ``build_four_plan_backend_contract.py``.
    output_dir:
        Directory for command reports and roundtrip/mutation artifacts.
    run_mutate:
        Whether to ask the backend to mutate.  Keep ``False`` until dry-run,
        roundtrip, and verify-only all pass on a real backend.
    mutation_kind:
        Forwarded to the backend when running dry-run/mutate.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    prefix = _backend_arg_prefix(backend)

    command_results: List[CommandResult] = []

    cap_report = output_dir / "backend_capabilities.json"
    cap_result = _run("print_capabilities", prefix + ["--print-capabilities"])
    command_results.append(cap_result)
    capabilities = _capability_object(cap_result, cap_report)

    inventory_report = output_dir / "backend_inventory.json"
    command_results.append(_run(
        "inventory",
        prefix + ["--inventory", "--input", str(ir_path), "--report", str(inventory_report)],
        report_path=inventory_report,
    ))

    roundtrip_ir = output_dir / "roundtrip.hivm.mlir"
    roundtrip_report = output_dir / "backend_roundtrip.json"
    command_results.append(_run(
        "roundtrip",
        prefix + ["--roundtrip", "--input", str(ir_path), "--output", str(roundtrip_ir), "--report", str(roundtrip_report)],
        report_path=roundtrip_report,
        output_path=roundtrip_ir,
    ))

    verify_report = output_dir / "backend_verify.json"
    command_results.append(_run(
        "verify_only",
        prefix + ["--verify-only", "--input", str(roundtrip_ir), "--report", str(verify_report)],
        report_path=verify_report,
    ))

    dry_run_report = output_dir / "backend_dry_run_contract.json"
    command_results.append(_run(
        "dry_run_contract",
        prefix + [
            "--dry-run",
            "--input", str(ir_path),
            "--edit-script", str(contract_path),
            "--mutation-kind", mutation_kind,
            "--report", str(dry_run_report),
        ],
        report_path=dry_run_report,
    ))

    mutate_report: Optional[Path] = None
    mutated_ir: Optional[Path] = None
    if run_mutate:
        mutated_ir = output_dir / "optimized.backend_contract_mutated.hivm.mlir"
        mutate_report = output_dir / "backend_mutate_contract.json"
        command_results.append(_run(
            "mutate_contract",
            prefix + [
                "--mutate",
                "--input", str(ir_path),
                "--output", str(mutated_ir),
                "--edit-script", str(contract_path),
                "--mutation-kind", mutation_kind,
                "--report", str(mutate_report),
            ],
            report_path=mutate_report,
            output_path=mutated_ir,
        ))

    report_files = {
        "capabilities": cap_report,
        "inventory": inventory_report,
        "roundtrip": roundtrip_report,
        "verify": verify_report,
        "dry_run": dry_run_report,
    }
    if mutate_report:
        report_files["mutate"] = mutate_report

    loaded_reports = {key: _load_json_if_exists(path) for key, path in report_files.items()}
    is_real_backend = bool(loaded_reports.get("capabilities", {}).get("is_real_mlir_backend"))
    all_required_commands_ok = all(x.ok for x in command_results if x.name != "mutate_contract")
    dry_run_obj = loaded_reports.get("dry_run", {})

    summary = {
        "schema_version": RUNNER_SCHEMA_VERSION,
        "backend": str(backend),
        "input_ir": str(ir_path),
        "contract": str(contract_path),
        "output_dir": str(output_dir),
        "is_real_mlir_backend": is_real_backend,
        "run_mutate_requested": run_mutate,
        "all_required_commands_ok": all_required_commands_ok,
        "command_results": [x.to_json() for x in command_results],
        "report_files": {k: str(v) for k, v in report_files.items()},
        "loaded_report_status": {k: v.get("status") or v.get("schema_version") for k, v in loaded_reports.items()},
        "dry_run_action_count": dry_run_obj.get("action_count"),
        "dry_run_located_action_count": dry_run_obj.get("located_action_count"),
        "production_rewrite_claim_allowed": bool(
            is_real_backend and all_required_commands_ok and run_mutate and loaded_reports.get("mutate", {}).get("mutation_performed")
        ),
        "decision": "READY_FOR_USER_REAL_BACKEND_RUN" if not is_real_backend else "REAL_BACKEND_DRY_RUN_COMPLETED",
        "notes": [
            "Fake backend validates CLI/report plumbing only; it is not production rewrite evidence.",
            "Do not enable mutation on a real backend until inventory, roundtrip, verify-only, and dry-run pass.",
            "Mutation success still requires post-mutate verify/DES/trace before claiming real four-Plan rewrite.",
        ],
    }
    summary_path = output_dir / "backend_contract_execution_summary.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    return summary
