# -*- coding: utf-8 -*-
"""Candidate-space generation and layered/exhaustive search facade."""
from .core import (
    get_available_cores,
    tile_key,
    estimate_num_tiles_for_tile,
    generate_block_dim_candidates_for_tile,
    select_default_block_dim_for_tile,
    build_cv_pipeline_plan_candidates,
    eligible_multibuffer_buffers,
    generate_per_buffer_multiplier_candidates,
    per_buffer_extra_bytes_by_scope,
    per_buffer_overlap_bonus,
    apply_v2_focus_space,
    refresh_dynamic_candidate_space,
    iter_layer1_raw_candidates,
    generate_aligned_dim_values,
    auto_generate_search_space,
    merge_search_space,
    estimate_search_space_size,
    apply_guided_search_adjustments,
    problem_shape,
    coarse_cost_for_layer1,
    search_tiling_fusion,
    alloc_overlap,
    refine_inner,
    dedup_strategy_candidates,
    build_layered_candidates,
    build_exhaustive_candidates,
    _compact_search_for_quality_audit,
    _score_candidate_pool_for_audit,
    build_search_quality_audit,
    strategy_diagnosis_bias,
    build_diagnosis_hints,
)
