#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build four-Plan rewrite readiness reports.

This command is safe to run without a real vTriton backend.  It only reads the
input IR and selected_plan.json, then emits candidate/legality/mutation-plan
reports for SyncPlan, MultiBufferPlan, CVPipelinePlan, and TilingPlan.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from strategy_search.rewrite_readiness import build_readiness_reports


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True, help="Input .hivm.mlir/.mlir file")
    ap.add_argument("--selected-plan", required=True, help="selected_plan.json generated by strategy search")
    ap.add_argument("--output-dir", required=True, help="Directory for rewrite readiness reports")
    args = ap.parse_args()
    paths = build_readiness_reports(Path(args.ir), Path(args.selected_plan), Path(args.output_dir))
    print("Generated rewrite readiness reports:")
    for name, path in paths.items():
        print(f"  {name}: {path}")


if __name__ == "__main__":
    main()
