#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build backend-facing contracts for four-Plan HIVM rewrite."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from strategy_search.backend_contract import build_backend_contract_reports


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True, help="Input .hivm.mlir/.mlir file")
    ap.add_argument("--selected-plan", required=True, help="selected_plan.json generated by strategy search")
    ap.add_argument("--output-dir", required=True, help="Directory for backend contract reports")
    args = ap.parse_args()
    paths = build_backend_contract_reports(Path(args.ir), Path(args.selected_plan), Path(args.output_dir))
    print("Generated four-Plan backend contract reports:")
    for name, path in paths.items():
        print(f"  {name}: {path}")


if __name__ == "__main__":
    main()
