//===- hivm_operation_backend.cpp - V4.2 HIVM backend adapter --------===//
//
// This file is generated by strategy_search_demo Phase-6D.
// It is intended to be built inside the vTriton source tree and to call the
// real HivmOpsEditor API, rather than performing Python/text-only rewrites.
//
// Official MLIR discipline followed here:
//   - load MLIR with registered dialects;
//   - inspect Operation objects via HivmOpsEditor/listOps;
//   - use HivmOpsEditor/MLIR APIs for roundtrip and guarded mutations;
//   - do not claim Q-load hoist until dominance/region-motion proof exists.
//
//===----------------------------------------------------------------------===//

#include "AscendModel/Transforms/HivmOpsEditor.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Verifier.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/raw_ostream.h"

#ifdef TRITONSIM_HAS_BISHENGIR_HIVM
#include "bishengir/Dialect/Annotation/IR/Annotation.h"
#include "bishengir/Dialect/HACC/IR/HACC.h"
#endif

#include <string>
#include <fstream>
#include <regex>
#include <vector>
#include <set>
#include <sstream>

using namespace mlir;
using namespace mlir::ascend;

static llvm::cl::opt<std::string> inputFilename("input", llvm::cl::desc("Input HIVM/NPUIR MLIR file"), llvm::cl::init(""));
static llvm::cl::opt<std::string> outputFilename("output", llvm::cl::desc("Output MLIR file"), llvm::cl::init(""));
static llvm::cl::opt<std::string> reportFilename("report", llvm::cl::desc("JSON report file"), llvm::cl::init(""));
static llvm::cl::opt<std::string> editScriptFilename("edit-script", llvm::cl::desc("Strategy/dry-run/mutation JSON script"), llvm::cl::init(""));
static llvm::cl::opt<std::string> mutationKind(
    "mutation-kind",
    llvm::cl::desc("gm_roundtrip_deletion|sync_event_insertion|multibuffer_clone|cv_pipeline_stage_reorder|tiling_loop_split|q_load_hoist"),
    llvm::cl::init(""));
static llvm::cl::opt<unsigned> maxGMPairs("max-gm-pairs", llvm::cl::desc("Maximum GM round-trip pairs to remove in guarded prototype"), llvm::cl::init(0));

static llvm::cl::opt<bool> printCapabilities("print-capabilities", llvm::cl::desc("Print backend capabilities JSON"));
static llvm::cl::opt<bool> inventoryMode("inventory", llvm::cl::desc("List operation inventory"));
static llvm::cl::opt<bool> roundtripMode("roundtrip", llvm::cl::desc("Read and write MLIR without optimization"));
static llvm::cl::opt<bool> verifyOnlyMode("verify-only", llvm::cl::desc("Parse and verify input"));
static llvm::cl::opt<bool> dryRunMode("dry-run", llvm::cl::desc("Dry-run edit script without mutation"));
static llvm::cl::opt<bool> mutateMode("mutate", llvm::cl::desc("Run guarded mutation"));

static void writeFileOrStdout(llvm::StringRef path, llvm::StringRef text) {
  if (path.empty() || path == "-") {
    llvm::outs() << text;
    return;
  }
  std::error_code ec;
  llvm::raw_fd_ostream os(path, ec, llvm::sys::fs::OF_Text);
  if (ec) {
    llvm::errs() << "cannot open report file " << path << ": " << ec.message() << "\n";
    return;
  }
  os << text;
}

static std::string jsonEscape(llvm::StringRef s) {
  std::string out;
  for (char c : s) {
    switch (c) {
    case '"': out += "\\\""; break;
    case '\\': out += "\\\\"; break;
    case '\n': out += "\\n"; break;
    case '\r': out += "\\r"; break;
    case '\t': out += "\\t"; break;
    default: out += c; break;
    }
  }
  return out;
}

static void registerDialects(DialectRegistry &registry) {
#ifdef TRITONSIM_HAS_BISHENGIR_HIVM
  registry.insert<mlir::hivm::HIVMDialect>();
  registry.insert<mlir::annotation::AnnotationDialect>();
  registry.insert<mlir::hacc::HACCDialect>();
#endif
  registry.insert<arith::ArithDialect>();
  registry.insert<func::FuncDialect>();
  registry.insert<memref::MemRefDialect>();
  registry.insert<scf::SCFDialect>();
  registry.insert<tensor::TensorDialect>();
  registry.insert<mlir::bufferization::BufferizationDialect>();
}

static std::string capabilitiesJson() {
#ifdef TRITONSIM_HAS_BISHENGIR_HIVM
  const char *real = "true";
#else
  const char *real = "false";
#endif
  std::string s;
  s += "{\n";
  s += "  \"schema_version\": \"hivm_operation_backend_capabilities_v4_4\",\n";
  s += "  \"backend_kind\": \"hivmopseditor_adapter\",\n";
  s += "  \"is_real_mlir_backend\": "; s += real; s += ",\n";
  s += "  \"uses_hivmopseditor\": "; s += real; s += ",\n";
  s += "  \"uses_mlir_operation_walk\": "; s += real; s += ",\n";
  s += "  \"inventory\": true,\n";
  s += "  \"roundtrip\": true,\n";
  s += "  \"verify_only\": true,\n";
  s += "  \"dry_run\": true,\n";
  s += "  \"sync_per_action_locator_dry_run\": true,\n";
  s += "  \"hivmopseditor_load_export_list_ops\": true,\n";
  s += "  \"hivmopseditor_insert_sync_ops_api_available\": true,\n";
  s += "  \"hivmopseditor_gm_roundtrip_delete_api_available\": true,\n";
  s += "  \"hivmopseditor_buffer_clone_api_available\": false,\n";
  s += "  \"hivmopseditor_replace_uses_api_available\": false,\n";
  s += "  \"hivmopseditor_region_motion_api_available\": false,\n";
  s += "  \"hivmopseditor_loop_split_api_available\": false,\n";
  s += "  \"mutate_sync_event_insertion\": true,\n";
  s += "  \"sync_event_liveness_proof_available\": false,\n";
  s += "  \"sync_deadlock_proof_available\": false,\n";
  s += "  \"mutate_multibuffer_clone\": false,\n";
  s += "  \"mutate_cv_pipeline_stage_reorder\": false,\n";
  s += "  \"mutate_tiling_loop_split\": false,\n";
  s += "  \"mutate_q_load_hoist\": false,\n";
  s += "  \"mutate_gm_roundtrip_deletion\": true,\n";
  s += "  \"notes\": [\"V4.4 adds guarded HivmOpsEditor SyncPlan mutation prototype for one pipe_barrier action\", \"backend is intentionally hivm-crud-style: parse/list/export first, guarded mutation second\", \"sync insertion mutation is enabled only for one guarded barrier_to_directional_event_pair action; it remains prototype until real verifier/DES confirms it\", \"gm_roundtrip_deletion delegates only to current HivmOpsEditor guarded prototype and must remain limited by max-gm-pairs\", \"MultiBuffer/CVPipeline/Tiling require new operation-level APIs for buffer cloning, use replacement, region motion, loop split, and verification\"]\n";
  s += "}\n";
  return s;
}

struct DryRunAction {
  std::string actionId;
  std::string mutationKind;
  std::string eventId;
  std::string setPipe;
  std::string waitPipe;
  int targetLine = -1;
  std::vector<int> candidateLines;
};

static std::string readTextFileBestEffort(llvm::StringRef path) {
  if (path.empty()) return "";
  std::ifstream in{std::string(path)};
  if (!in) return "";
  std::ostringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

static std::string regexFirst(const std::string &text, const std::regex &rx) {
  std::smatch m;
  if (std::regex_search(text, m, rx) && m.size() >= 2) return m[1].str();
  return "";
}

static std::vector<int> regexAllInts(const std::string &text, const std::regex &rx) {
  std::vector<int> out;
  auto begin = std::sregex_iterator(text.begin(), text.end(), rx);
  auto end = std::sregex_iterator();
  for (auto it = begin; it != end; ++it) {
    try { out.push_back(std::stoi((*it)[1].str())); } catch (...) {}
  }
  return out;
}

static std::vector<DryRunAction> parseEditScriptActionsBestEffort(const std::string &text) {
  std::vector<DryRunAction> out;
  if (text.empty()) return out;
  std::regex actionRx("\\\"action_id\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"");
  auto begin = std::sregex_iterator(text.begin(), text.end(), actionRx);
  auto end = std::sregex_iterator();
  std::vector<std::pair<size_t, std::string>> ids;
  for (auto it = begin; it != end; ++it) ids.push_back({(size_t)it->position(), (*it)[1].str()});
  for (size_t i = 0; i < ids.size(); ++i) {
    size_t start = ids[i].first;
    size_t stop = (i + 1 < ids.size()) ? ids[i + 1].first : text.size();
    std::string win = text.substr(start, stop - start);
    DryRunAction a;
    a.actionId = ids[i].second;
    a.mutationKind = regexFirst(win, std::regex("\\\"mutation_kind\\\"\\s*:\\s*\\\"([^\\\"]+)\\\""));
    a.eventId = regexFirst(win, std::regex("\\\"event_id\\\"\\s*:\\s*\\\"([^\\\"]+)\\\""));
    a.setPipe = regexFirst(win, std::regex("\\\"set_pipe\\\"\\s*:\\s*\\\"?([^\\\",}]+)\\\"?"));
    a.waitPipe = regexFirst(win, std::regex("\\\"wait_pipe\\\"\\s*:\\s*(?:\\\"([^\\\"]+)\\\"|null)"));
    if (a.waitPipe.empty()) a.waitPipe = a.setPipe;
    if (a.eventId.empty()) {
      std::smatch em;
      std::regex aidEvent("sync_check_event_([A-Za-z0-9_]+)");
      if (std::regex_search(a.actionId, em, aidEvent) && em.size() >= 2) a.eventId = em[1].str();
    }
    a.candidateLines = regexAllInts(win, std::regex("\\\"line\\\"\\s*:\\s*([0-9]+)"));
    if (!a.candidateLines.empty()) a.targetLine = a.candidateLines.front();
    out.push_back(a);
  }
  return out;
}

#ifdef TRITONSIM_HAS_BISHENGIR_HIVM
static OwningOpRef<ModuleOp> loadModule(MLIRContext &ctx, llvm::StringRef input) {
  return HivmOpsEditor::loadFromFile(ctx, input);
}

static int opLine(Operation *op) {
  if (!op) return -1;
  if (auto loc = dyn_cast<FileLineColLoc>(op->getLoc())) return (int)loc.getLine();
  return -1;
}

static std::string opToString(Operation *op) {
  if (!op) return "";
  std::string buf;
  llvm::raw_string_ostream os(buf);
  op->print(os);
  os.flush();
  return buf;
}

static bool hasCandidateLine(const DryRunAction &a, int line) {
  if (line < 0) return false;
  for (int x : a.candidateLines) if (x == line) return true;
  return false;
}

static bool nameContains(llvm::StringRef name, llvm::StringRef frag) {
  return name.find(frag) != llvm::StringRef::npos;
}

static std::string locateSyncActionJson(const DryRunAction &a, const SmallVector<HivmOpInfo> &ops) {
  std::vector<const HivmOpInfo*> matched;
  bool sawSet = false, sawWait = false, sawBarrier = false, sawSyncBlock = false;
  for (auto &info : ops) {
    llvm::StringRef name(info.qualifiedName);
    int line = opLine(info.op);
    std::string text = opToString(info.op);
    bool match = false;
    if (!a.eventId.empty() && text.find(a.eventId) != std::string::npos &&
        (nameContains(name, "set_flag") || nameContains(name, "wait_flag"))) {
      match = true;
    }
    if (!match && hasCandidateLine(a, line)) {
      if (a.mutationKind == "validate_existing_event_pair_liveness" &&
          (nameContains(name, "set_flag") || nameContains(name, "wait_flag"))) match = true;
      if (a.mutationKind == "barrier_to_directional_event_pair" &&
          (nameContains(name, "pipe_barrier") || nameContains(name, "barrier"))) match = true;
      if (a.mutationKind == "classify_sync_block_scope" && nameContains(name, "sync_block")) match = true;
    }
    if (match) {
      matched.push_back(&info);
      if (nameContains(name, "set_flag")) sawSet = true;
      if (nameContains(name, "wait_flag")) sawWait = true;
      if (nameContains(name, "pipe_barrier") || nameContains(name, "barrier")) sawBarrier = true;
      if (nameContains(name, "sync_block")) sawSyncBlock = true;
    }
  }

  bool located = !matched.empty();
  bool eventPair = sawSet && sawWait;
  bool barrierLocated = sawBarrier;
  bool syncBlockLocated = sawSyncBlock;
  std::string rep;
  rep += "{\"action_id\": \"" + jsonEscape(a.actionId) + "\", ";
  rep += "\"mutation_kind\": \"" + jsonEscape(a.mutationKind) + "\", ";
  rep += "\"event_id\": "; rep += a.eventId.empty() ? "null" : "\"" + jsonEscape(a.eventId) + "\""; rep += ", ";
  rep += "\"target_line\": "; rep += a.targetLine >= 0 ? std::to_string(a.targetLine) : "null"; rep += ", ";
  rep += "\"operation_found\": "; rep += located ? "true" : "false"; rep += ", ";
  rep += "\"located\": "; rep += located ? "true" : "false"; rep += ", ";
  rep += "\"locator\": {\"strategy\": \"event_id_or_contract_line_against_HivmOpsEditor_listOps\", ";
  rep += "\"matched_operation_count\": " + std::to_string(matched.size()) + ", ";
  rep += "\"matched_ops\": [";
  for (size_t i = 0; i < matched.size(); ++i) {
    auto *m = matched[i];
    rep += "{\"index\": " + std::to_string(m->index) + ", \"name\": \"" + jsonEscape(m->qualifiedName) + "\", \"line\": ";
    int line = opLine(m->op); rep += line >= 0 ? std::to_string(line) : "null";
    rep += "}";
    if (i + 1 != matched.size()) rep += ", ";
  }
  rep += "]}, ";
  rep += "\"checks\": {";
  rep += "\"backend_parsed_event_operands\": "; rep += (!a.eventId.empty() && located) ? "true" : "false"; rep += ", ";
  rep += "\"event_pairs_reported\": "; rep += eventPair ? "true" : "false"; rep += ", ";
  rep += "\"event_liveness_passed\": false, ";
  rep += "\"no_deadlock_or_conflict_reported\": false, ";
  rep += "\"target_barrier_located_by_backend\": "; rep += barrierLocated ? "true" : "false"; rep += ", ";
  rep += "\"producer_consumer_pair_reported\": false, ";
  rep += "\"fresh_or_safe_reused_event_reported\": false, ";
  rep += "\"backend_can_print_official_set_wait_ops\": false, ";
  rep += "\"event_liveness_passes_after_dry_run_plan\": false, ";
  rep += "\"backend_reports_sync_block_mode_and_scope\": "; rep += syncBlockLocated ? "true" : "false";
  rep += "}, ";
  rep += "\"blockers\": [";
  bool needComma = false;
  auto addBlocker = [&](const std::string &b) { if (needComma) rep += ", "; rep += "\"" + jsonEscape(b) + "\""; needComma = true; };
  if (!located) addBlocker("sync_target_not_located_by_real_backend");
  addBlocker("event_liveness_proof_not_implemented_yet");
  addBlocker("deadlock_check_not_implemented_yet");
  if (a.mutationKind == "barrier_to_directional_event_pair") addBlocker("producer_consumer_dependency_proof_not_implemented_yet");
  rep += "]}";
  return rep;
}

static std::string normalizeEnumToken(std::string s) {
  while (!s.empty() && (s.front() == '<' || s.front() == '%' || s.front() == ' ' || s.front() == '\"')) s.erase(s.begin());
  while (!s.empty() && (s.back() == '>' || s.back() == ' ' || s.back() == '\"')) s.pop_back();
  return s;
}

static bool parsePipeAttr(MLIRContext *ctx, const std::string &raw, hivm::PipeAttr &out) {
  std::string p = normalizeEnumToken(raw);
  if (p == "PIPE_V") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_V); return true; }
  if (p == "PIPE_M") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_M); return true; }
  if (p == "PIPE_S") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_S); return true; }
  if (p == "PIPE_MTE1") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_MTE1); return true; }
  if (p == "PIPE_MTE2") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_MTE2); return true; }
  if (p == "PIPE_MTE3") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_MTE3); return true; }
  if (p == "PIPE_FIX") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_FIX); return true; }
  if (p == "PIPE_ALL") { out = hivm::PipeAttr::get(ctx, hivm::PIPE::PIPE_ALL); return true; }
  return false;
}

static bool parseEventAttr(MLIRContext *ctx, const std::string &raw, hivm::EventAttr &out) {
  std::string e = normalizeEnumToken(raw);
  // Contract-created barrier rewrites use a backend-owned safe default unless
  // an official EVENT_ID token is explicitly provided by the contract.
  if (e.empty() || e.find("hivm_sync_auto") != std::string::npos) {
    out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID0);
    return true;
  }
  if (e == "EVENT_ID0") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID0); return true; }
  if (e == "EVENT_ID1") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID1); return true; }
  if (e == "EVENT_ID2") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID2); return true; }
  if (e == "EVENT_ID3") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID3); return true; }
  if (e == "EVENT_ID4") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID4); return true; }
  if (e == "EVENT_ID5") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID5); return true; }
  if (e == "EVENT_ID6") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID6); return true; }
  if (e == "EVENT_ID7") { out = hivm::EventAttr::get(ctx, hivm::EVENT::EVENT_ID7); return true; }
  return false;
}

static Operation *locateSingleBarrierForMutation(const DryRunAction &a, const SmallVector<HivmOpInfo> &ops) {
  Operation *match = nullptr;
  for (auto &info : ops) {
    llvm::StringRef name(info.qualifiedName);
    if (!(nameContains(name, "pipe_barrier") || nameContains(name, "barrier"))) continue;
    int line = opLine(info.op);
    if (hasCandidateLine(a, line) || (a.targetLine >= 0 && line == a.targetLine)) {
      if (match) return nullptr; // Ambiguous: guarded mutation requires exactly one target.
      match = info.op;
    }
  }
  return match;
}

static std::string mutateSingleSyncBarrierAction(HivmOpsEditor &editor, const DryRunAction &a) {
  auto ops = editor.listOps();
  Operation *target = locateSingleBarrierForMutation(a, ops);
  std::string rep;
  rep += "{\"action_id\": \"" + jsonEscape(a.actionId) + "\", ";
  rep += "\"mutation_kind\": \"" + jsonEscape(a.mutationKind) + "\", ";
  rep += "\"target_line\": "; rep += a.targetLine >= 0 ? std::to_string(a.targetLine) : "null"; rep += ", ";
  if (!target) {
    rep += "\"mutation_performed\": false, \"status\": \"blocked_target_not_found_or_ambiguous\"}";
    return rep;
  }
  if (a.mutationKind != "barrier_to_directional_event_pair") {
    rep += "\"mutation_performed\": false, \"status\": \"blocked_non_barrier_sync_action\"}";
    return rep;
  }
  MLIRContext *ctx = target->getContext();
  hivm::PipeAttr setPipe, waitPipe;
  hivm::EventAttr eventAttr;
  if (!parsePipeAttr(ctx, a.setPipe, setPipe)) {
    rep += "\"mutation_performed\": false, \"status\": \"blocked_unparseable_set_pipe\", \"set_pipe\": \"" + jsonEscape(a.setPipe) + "\"}";
    return rep;
  }
  if (!parsePipeAttr(ctx, a.waitPipe.empty() ? a.setPipe : a.waitPipe, waitPipe)) {
    rep += "\"mutation_performed\": false, \"status\": \"blocked_unparseable_wait_pipe\", \"wait_pipe\": \"" + jsonEscape(a.waitPipe) + "\"}";
    return rep;
  }
  if (!parseEventAttr(ctx, a.eventId, eventAttr)) {
    rep += "\"mutation_performed\": false, \"status\": \"blocked_unparseable_event_id\", \"event_id\": \"" + jsonEscape(a.eventId) + "\"}";
    return rep;
  }

  editor.addSetFlagWaitFlagBefore(target, setPipe, waitPipe, eventAttr);
  editor.deleteOp(target);
  rep += "\"mutation_performed\": true, ";
  rep += "\"status\": \"completed_hivmopseditor_sync_barrier_rewrite_prototype\", ";
  rep += "\"set_pipe\": \"" + jsonEscape(a.setPipe) + "\", ";
  rep += "\"wait_pipe\": \"" + jsonEscape(a.waitPipe.empty() ? a.setPipe : a.waitPipe) + "\", ";
  rep += "\"event_id\": \"" + jsonEscape(a.eventId.empty() ? "EVENT_ID0" : a.eventId) + "\"}";
  return rep;
}

#endif

int main(int argc, char **argv) {
  llvm::InitLLVM y(argc, argv);
  llvm::cl::ParseCommandLineOptions(argc, argv, "Phase-6D HIVM Operation backend adapter\n");

  if (printCapabilities) {
    llvm::outs() << capabilitiesJson();
    return 0;
  }

#ifndef TRITONSIM_HAS_BISHENGIR_HIVM
  std::string rep = "{\n  \"status\": \"failed_backend_not_built_with_hivm\",\n  \"is_real_mlir_backend\": false,\n  \"blockers\": [\"TRITONSIM_HAS_BISHENGIR_HIVM is not enabled\"]\n}\n";
  writeFileOrStdout(reportFilename, rep);
  return 2;
#else
  if (inputFilename.empty()) {
    llvm::errs() << "--input is required for this mode\n";
    return 1;
  }
  DialectRegistry registry;
  registerDialects(registry);
  MLIRContext ctx(registry);
  ctx.loadAllAvailableDialects();

  auto module = loadModule(ctx, inputFilename);
  if (!module) {
    std::string rep = "{\n  \"status\": \"parse_failed\",\n  \"input\": \"" + jsonEscape(inputFilename) + "\"\n}\n";
    writeFileOrStdout(reportFilename, rep);
    return 3;
  }
  HivmOpsEditor editor(*module);

  if (inventoryMode) {
    auto ops = editor.listOps();
    std::string rep;
    rep += "{\n  \"status\": \"passed_inventory\",\n";
    rep += "  \"input\": \"" + jsonEscape(inputFilename) + "\",\n";
    rep += "  \"op_count\": " + std::to_string(ops.size()) + ",\n";
    rep += "  \"ops\": [\n";
    for (size_t i = 0; i < ops.size(); ++i) {
      rep += "    {\"index\": " + std::to_string(ops[i].index) + ", \"name\": \"" + jsonEscape(ops[i].qualifiedName) + "\", \"line\": ";
      int line = opLine(ops[i].op);
      rep += line >= 0 ? std::to_string(line) : "null";
      rep += "}";
      if (i + 1 != ops.size()) rep += ",";
      rep += "\n";
    }
    rep += "  ]\n}\n";
    writeFileOrStdout(reportFilename, rep);
    return 0;
  }

  if (verifyOnlyMode) {
    bool ok = succeeded(mlir::verify(*module));
    std::string rep = "{\n  \"status\": \"";
    rep += ok ? "passed_verify" : "failed_verify";
    rep += "\",\n  \"input\": \"" + jsonEscape(inputFilename) + "\"\n}\n";
    writeFileOrStdout(reportFilename, rep);
    return ok ? 0 : 4;
  }

  if (roundtripMode) {
    if (outputFilename.empty()) {
      llvm::errs() << "--output is required for --roundtrip\n";
      return 1;
    }
    bool ok = succeeded(editor.exportToFile(outputFilename));
    std::string rep = "{\n  \"status\": \"";
    rep += ok ? "passed_roundtrip" : "failed_roundtrip";
    rep += "\",\n  \"input\": \"" + jsonEscape(inputFilename) + "\",\n  \"output\": \"" + jsonEscape(outputFilename) + "\"\n}\n";
    writeFileOrStdout(reportFilename, rep);
    return ok ? 0 : 5;
  }

  if (dryRunMode) {
    auto ops = editor.listOps();
    std::string editText = readTextFileBestEffort(editScriptFilename);
    auto actions = parseEditScriptActionsBestEffort(editText);
    std::string rep;
    rep += "{\n  \"schema_version\": \"hivm_operation_backend_dryrun_v3\",\n";
    rep += "  \"status\": \"passed_operation_backend_dry_run\",\n";
    rep += "  \"backend\": \"hivmopseditor_adapter\",\n";
    rep += "  \"is_real_mlir_backend\": true,\n";
    rep += "  \"input\": \"" + jsonEscape(inputFilename) + "\",\n";
    rep += "  \"edit_script\": \"" + jsonEscape(editScriptFilename) + "\",\n";
    rep += "  \"mutation_kind\": \"" + jsonEscape(mutationKind) + "\",\n";
    rep += "  \"op_count\": " + std::to_string(ops.size()) + ",\n";
    rep += "  \"action_count\": " + std::to_string(actions.size()) + ",\n";
    unsigned locatedCount = 0;
    std::vector<std::string> actionReports;
    for (auto &a : actions) {
      std::string one = locateSyncActionJson(a, ops);
      if (one.find("\"located\": true") != std::string::npos) locatedCount++;
      actionReports.push_back(one);
    }
    rep += "  \"located_action_count\": " + std::to_string(locatedCount) + ",\n";
    rep += "  \"mutation_performed\": false,\n";
    rep += "  \"actions\": [\n";
    for (size_t i = 0; i < actionReports.size(); ++i) {
      rep += "    " + actionReports[i];
      if (i + 1 != actionReports.size()) rep += ",";
      rep += "\n";
    }
    rep += "  ],\n";
    rep += "  \"notes\": [\"This V4.2 dry-run locates SyncPlan actions against HivmOpsEditor listOps plus operation locations/printed text. Event liveness, deadlock, and producer-consumer dependency proofs remain explicit future backend work.\"]\n";
    rep += "}\n";
    writeFileOrStdout(reportFilename, rep);
    return 0;
  }

  if (mutateMode) {
    if (outputFilename.empty()) {
      llvm::errs() << "--output is required for --mutate\n";
      return 1;
    }
    if (mutationKind == "gm_roundtrip_deletion") {
      unsigned before = editor.listOps().size();
      if (maxGMPairs > 0) {
        editor.removeRedundantLoadStorePair(maxGMPairs);
      }
      unsigned after = editor.listOps().size();
      bool wrote = succeeded(editor.exportToFile(outputFilename));
      bool changed = after < before;
      std::string rep;
      rep += "{\n  \"status\": \"";
      rep += (wrote ? "completed_guarded_gm_roundtrip_mutation" : "failed_export_after_mutation");
      rep += "\",\n  \"mutation_kind\": \"gm_roundtrip_deletion\",\n";
      rep += "  \"input\": \"" + jsonEscape(inputFilename) + "\",\n  \"output\": \"" + jsonEscape(outputFilename) + "\",\n";
      rep += "  \"max_gm_pairs\": " + std::to_string(maxGMPairs) + ",\n";
      rep += "  \"op_count_before\": " + std::to_string(before) + ",\n";
      rep += "  \"op_count_after\": " + std::to_string(after) + ",\n";
      rep += "  \"mutation_performed\": "; rep += changed ? "true" : "false"; rep += ",\n";
      rep += "  \"production_warning\": \"This uses the current HivmOpsEditor convenience method. It must be combined with external alias/observable-boundary proof before broad production use.\"\n";
      rep += "}\n";
      writeFileOrStdout(reportFilename, rep);
      return wrote ? 0 : 6;
    }
    if (mutationKind == "q_load_hoist") {
      std::string rep = "{\n  \"status\": \"rejected_q_load_hoist_not_implemented_in_real_backend\",\n  \"mutation_kind\": \"q_load_hoist\",\n  \"mutation_performed\": false,\n  \"blockers\": [\"dominance_and_region_motion_algorithm_not_implemented\", \"do_not_use_text_region_motion_for_production\"]\n}\n";
      writeFileOrStdout(reportFilename, rep);
      return 7;
    }
    if (mutationKind == "sync_event_insertion") {
      std::string editText = readTextFileBestEffort(editScriptFilename);
      auto actions = parseEditScriptActionsBestEffort(editText);
      std::vector<DryRunAction> candidates;
      for (auto &a : actions) {
        if (a.mutationKind == "barrier_to_directional_event_pair") candidates.push_back(a);
      }
      std::string rep;
      rep += "{\n  \"schema_version\": \"hivm_sync_backend_mutation_report_v4_4\",\n";
      rep += "  \"status\": ";
      if (candidates.empty()) {
        rep += "\"blocked_no_barrier_to_directional_event_pair_action\",\n";
        rep += "  \"mutation_performed\": false,\n  \"actions\": []\n}\n";
        writeFileOrStdout(reportFilename, rep);
        return 9;
      }
      if (candidates.size() != 1) {
        rep += "\"blocked_requires_exactly_one_sync_action\",\n";
        rep += "  \"mutation_performed\": false,\n  \"candidate_action_count\": " + std::to_string(candidates.size()) + "\n}\n";
        writeFileOrStdout(reportFilename, rep);
        return 9;
      }
      unsigned before = editor.listOps().size();
      std::string actionReport = mutateSingleSyncBarrierAction(editor, candidates.front());
      unsigned after = editor.listOps().size();
      bool actionChanged = actionReport.find("\"mutation_performed\": true") != std::string::npos;
      bool wrote = false;
      bool verified = false;
      if (actionChanged) {
        wrote = succeeded(editor.exportToFile(outputFilename));
        verified = succeeded(mlir::verify(*module));
      }
      rep += actionChanged && wrote && verified ? "\"completed_guarded_sync_mutation_prototype\",\n" : "\"failed_or_blocked_guarded_sync_mutation_prototype\",\n";
      rep += "  \"mutation_kind\": \"sync_event_insertion\",\n";
      rep += "  \"input\": \"" + jsonEscape(inputFilename) + "\",\n";
      rep += "  \"output\": \"" + jsonEscape(outputFilename) + "\",\n";
      rep += "  \"edit_script\": \"" + jsonEscape(editScriptFilename) + "\",\n";
      rep += "  \"mutation_performed\": "; rep += actionChanged ? "true" : "false"; rep += ",\n";
      rep += "  \"export_succeeded\": "; rep += wrote ? "true" : "false"; rep += ",\n";
      rep += "  \"verify_after_mutation\": "; rep += verified ? "true" : "false"; rep += ",\n";
      rep += "  \"op_count_before\": " + std::to_string(before) + ",\n";
      rep += "  \"op_count_after\": " + std::to_string(after) + ",\n";
      rep += "  \"actions\": [" + actionReport + "],\n";
      rep += "  \"production_rewrite_claim_allowed\": false,\n";
      rep += "  \"production_warning\": \"This is a V4.4 HivmOpsEditor guarded mutation prototype for exactly one pipe_barrier action. It still requires real vTriton build, verifier, DES/trace, and msprof validation before production claims.\"\n";
      rep += "}\n";
      writeFileOrStdout(reportFilename, rep);
      return (actionChanged && wrote && verified) ? 0 : 9;
    }
    if (mutationKind == "multibuffer_clone") {
      std::string rep = "{\n  \"status\": \"rejected_multibuffer_clone_api_missing\",\n  \"mutation_kind\": \"multibuffer_clone\",\n  \"mutation_performed\": false,\n  \"blockers\": [\"HivmOpsEditor has no production buffer clone API yet\", \"replace_all_uses_in_scope API/proof required\", \"capacity_and_liveness_proof_required\"]\n}\n";
      writeFileOrStdout(reportFilename, rep);
      return 10;
    }
    if (mutationKind == "cv_pipeline_stage_reorder") {
      std::string rep = "{\n  \"status\": \"rejected_cv_pipeline_region_motion_api_missing\",\n  \"mutation_kind\": \"cv_pipeline_stage_reorder\",\n  \"mutation_performed\": false,\n  \"blockers\": [\"operation_move_across_loop_api_required\", \"dominance_and_stage_dependency_proof_required\", \"requires_prior_sync_and_multibuffer_proofs\"]\n}\n";
      writeFileOrStdout(reportFilename, rep);
      return 11;
    }
    if (mutationKind == "tiling_loop_split") {
      std::string rep = "{\n  \"status\": \"rejected_tiling_loop_split_api_missing\",\n  \"mutation_kind\": \"tiling_loop_split\",\n  \"mutation_performed\": false,\n  \"blockers\": [\"loop_split_api_required\", \"index_remap_required\", \"load_store_slice_rewrite_required\", \"tail_mask_proof_required\"]\n}\n";
      writeFileOrStdout(reportFilename, rep);
      return 12;
    }
    std::string rep = "{\n  \"status\": \"unknown_mutation_kind\",\n  \"mutation_kind\": \"" + jsonEscape(mutationKind) + "\"\n}\n";
    writeFileOrStdout(reportFilename, rep);
    return 8;
  }

  editor.printSummary(llvm::outs());
  return 0;
#endif
}
